<a href="https://colab.research.google.com/github/kolumide1972/datasciencecoursera/blob/master/Data_analysis_with_python1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello")

hello


In [2]:
a=2
b=3
print(a+b)

5


In [4]:
import numpy as np
np.int8


numpy.int8

In [8]:
import numpy as np
np.array([1,2,3,4])


array([1, 2, 3, 4])

In [12]:
a=np.array([1,2,3,4])


In [13]:
b=np.array([0,0.5,1.0,1.5])

In [15]:
a[0],a[1]

(1, 2)

In [16]:
b[1],b[2]

(0.5, 1.0)

In [17]:
a[0:]

array([1, 2, 3, 4])

In [21]:
b[[0,1,-1]]

array([0. , 0.5, 1.5])

In [22]:
a

array([1, 2, 3, 4])

In [23]:
a.dtype

dtype('int64')

In [24]:
b.dtype

dtype('float64')

In [26]:
A=np.array([[1,2,3,],
 [4,5,6]])

In [27]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
A.dtype

dtype('int64')

In [29]:
A.shape

(2, 3)

In [30]:
A.ndim

2

In [31]:
A.size

6

In [32]:
B=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [37]:
B[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [8]:
import numpy as np
a= np.arange(4)

In [7]:
a=(1,2,3)

In [9]:
a

array([0, 1, 2, 3])

In [10]:
b=(10,20,30,40)

In [11]:
b

(10, 20, 30, 40)

In [12]:
b=np.arange(5)

In [13]:
b

array([0, 1, 2, 3, 4])

In [14]:
b+10

array([10, 11, 12, 13, 14])

In [15]:
b

array([0, 1, 2, 3, 4])

In [16]:
b+=100

In [17]:
b

array([100, 101, 102, 103, 104])

In [18]:
a=np.arange(5)

In [19]:
a

array([0, 1, 2, 3, 4])

In [20]:
a+20

array([20, 21, 22, 23, 24])

In [21]:
a=np.arange(7)

In [22]:
a

array([0, 1, 2, 3, 4, 5, 6])

In [23]:
a[0],a[2]

(0, 2)

In [26]:
a[[0,2]]

array([0, 2])

In [28]:
a[[True,False,False,True,False,False,True]]

array([0, 3, 6])

In [29]:
a

array([0, 1, 2, 3, 4, 5, 6])

In [30]:
a>=2

array([False, False,  True,  True,  True,  True,  True])

In [31]:
a[a>=2]

array([2, 3, 4, 5, 6])

In [32]:
a.mean()

3.0

In [33]:
a=np.arange(5)

In [34]:
a

array([0, 1, 2, 3, 4])

In [35]:
print(a<=3)

[ True  True  True  True False]
