<a href="https://colab.research.google.com/github/kolumide1972/datasciencecoursera/blob/master/Data_analysis_with_python1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

hello


In [ ]:
a=2
b=3
print(a+b)

5


In [ ]:
import numpy as np
np.int8


numpy.int8

In [ ]:
import numpy as np
np.array([1,2,3,4])


array([1, 2, 3, 4])

In [ ]:
a=np.array([1,2,3,4])


In [ ]:
b=np.array([0,0.5,1.0,1.5])

In [ ]:
a[0],a[1]

(1, 2)

In [ ]:
b[1],b[2]

(0.5, 1.0)

In [ ]:
a[0:]

array([1, 2, 3, 4])

In [ ]:
b[[0,1,-1]]

array([0. , 0.5, 1.5])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('float64')

In [ ]:
A=np.array([[1,2,3,],
 [4,5,6]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.dtype

dtype('int64')

In [ ]:
A.shape

(2, 3)

In [ ]:
A.ndim

2

In [ ]:
A.size

6

In [ ]:
B=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [ ]:
B[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
import numpy as np
a= np.arange(4)

In [ ]:
a=(1,2,3)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
b=(10,20,30,40)

In [ ]:
b

(10, 20, 30, 40)

In [ ]:
b=np.arange(5)

In [ ]:
b

array([0, 1, 2, 3, 4])

In [ ]:
b+10

array([10, 11, 12, 13, 14])

In [ ]:
b

array([0, 1, 2, 3, 4])

In [ ]:
b+=100

In [ ]:
b

array([100, 101, 102, 103, 104])

In [ ]:
a=np.arange(5)

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a+20

array([20, 21, 22, 23, 24])

In [ ]:
a=np.arange(7)

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
a[0],a[2]

(0, 2)

In [ ]:
a[[0,2]]

array([0, 2])

In [ ]:
a[[True,False,False,True,False,False,True]]

array([0, 3, 6])

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
a>=2

array([False, False,  True,  True,  True,  True,  True])

In [ ]:
a[a>=2]

array([2, 3, 4, 5, 6])

In [ ]:
a.mean()

3.0

In [ ]:
a=np.arange(5)

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
print(a<=3)

[ True  True  True  True False]


In [4]:
import pandas as pd
import numpy as np

In [5]:
# g7 countries are Canada,France,Germany,Italy,Japan,United Kingdom,United States#
g7_pop=pd.Series([35.67,63.95,60.47,67.9,127.65,69.34,311.23])

In [4]:
g7_pop

0     35.67
1     63.95
2     60.47
3     67.90
4    127.65
5     69.34
6    311.23
dtype: float64

In [6]:
g7_pop.name= "G& countries pouplation in millions"

In [7]:
g7_pop

0     35.67
1     63.95
2     60.47
3     67.90
4    127.65
5     69.34
6    311.23
Name: G& countries pouplation in millions, dtype: float64

In [10]:
g7_pop[0]

35.67

In [8]:
# g7 countries are Canada,France,Germany,Italy,Japan,United Kingdom,United States#
g7_pop.index=['Canada','France','Germany','Italy','Japan','United Kingdom','United States']

In [9]:
g7_pop

Canada             35.67
France             63.95
Germany            60.47
Italy              67.90
Japan             127.65
United Kingdom     69.34
United States     311.23
Name: G& countries pouplation in millions, dtype: float64

In [10]:
west_Africa=pd.Series([20,30.5,40.5,200,120.6],
                      index=['Garbon','Liberia','Ghana','Nigeria','Cameroon'],
                      name="Some West Africa Countries and Population")

In [11]:
west_Africa

Garbon       20.0
Liberia      30.5
Ghana        40.5
Nigeria     200.0
Cameroon    120.6
Name: Some West Africa Countries and Population, dtype: float64

In [12]:
g7_pop.Canada

35.67

In [13]:
west_Africa.Garbon

20.0

In [14]:
g7_pop['Canada']

35.67

In [15]:
g7_pop.iloc[-1]

311.23

In [16]:
g7_pop[['Canada','Italy']]

Canada    35.67
Italy     67.90
Name: G& countries pouplation in millions, dtype: float64

In [17]:
g7_pop['Canada']

35.67

In [18]:
g7_pop['Japan']

127.65

In [20]:
g7_pop.iloc[[0,1]]

Canada    35.67
France    63.95
Name: G& countries pouplation in millions, dtype: float64

In [23]:
g7_pop['Canada':'Italy']

Canada     35.67
France     63.95
Germany    60.47
Italy      67.90
Name: G& countries pouplation in millions, dtype: float64

In [24]:
g7_pop > 70

Canada            False
France            False
Germany           False
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: G& countries pouplation in millions, dtype: bool

In [25]:
g7_pop[g7_pop >70]

Japan            127.65
United States    311.23
Name: G& countries pouplation in millions, dtype: float64

In [26]:
g7_pop.mean()

105.17285714285715

In [27]:
g7_pop[g7_pop>g7_pop.mean()]

Japan            127.65
United States    311.23
Name: G& countries pouplation in millions, dtype: float64

In [29]:
g7_pop.std()

95.01433588574687

In [31]:
g7_pop[(g7_pop>g7_pop.mean()-g7_pop.std()/2) | (g7_pop>g7_pop.mean()+g7_pop.std()/2) ]

France             63.95
Germany            60.47
Italy              67.90
Japan             127.65
United Kingdom     69.34
United States     311.23
Name: G& countries pouplation in millions, dtype: float64

In [33]:
g7_pop[(g7_pop>80) & (g7_pop<200) ]

Japan    127.65
Name: G& countries pouplation in millions, dtype: float64

In [35]:
g7_pop['Canada']=40.5

In [37]:
g7_pop

Canada             40.50
France             63.95
Germany            60.47
Italy              67.90
Japan             127.65
United Kingdom     69.34
United States     311.23
Name: G& countries pouplation in millions, dtype: float64

Canada             40.50
France             63.95
Germany            60.47
Italy              67.90
Japan             127.65
United Kingdom     69.34
United States     311.23
Name: G& countries pouplation in millions, dtype: float64

In [42]:
from google.colab import files
uploaded = files.upload()


Saving coursea_data.csv to coursea_data.csv


In [48]:
import pandas as pd

# Assuming you uploaded a CSV file
# Replace 'your_uploaded_file.csv' with the name of the file you uploaded
file_name = 'coursea_data.csv'

df = pd.read_csv(file_name)




In [49]:
df

Unnamed: 0                                       course_title  \
0           134  (ISC)² Systems Security Certified Practitioner...   
1           743  A Crash Course in Causality:  Inferring Causal...   
2           874                     A Crash Course in Data Science   
3           413                            A Law Student's Toolkit   
4           635                A Life of Happiness and Fulfillment   
..          ...                                                ...   
886         236                         Программирование на Python   
887         883               Психолингвистика (Psycholinguistics)   
888         545       Разработка интерфейсов: вёрстка и JavaScript   
889         875                            Русский как иностранный   
890         163      Финансовые инструменты для частного инвестора   

                                   course_organization  \
0                                               (ISC)²   
1                           University of Pennsylvania   
2                             Johns Hopkins University   
3                                      Yale University   
4                            Indian School of Business   
..                                                 ...   
886                                      Mail.Ru Group   
887                  Saint Petersburg State University   
888                        E-Learning Development Fund   
889                  Saint Petersburg State University   
890  National Research University Higher School of ...   

    course_Certificate_type  course_rating course_difficulty  \
0            SPECIALIZATION            4.7          Beginner   
1                    COURSE            4.7      Intermediate   
2                    COURSE            4.5             Mixed   
3                    COURSE            4.7             Mixed   
4                    COURSE            4.8             Mixed   
..                      ...            ...               ...   
886          SPECIALIZATION            4.5      Intermediate   
887                  COURSE            4.8             Mixed   
888          SPECIALIZATION            4.5      Intermediate   
889          SPECIALIZATION            4.6      Intermediate   
890          SPECIALIZATION            4.7          Beginner   

    course_students_enrolled  
0                       5.3k  
1                        17k  
2                       130k  
3                        91k  
4                       320k  
..                       ...  
886                      52k  
887                      21k  
888                      30k  
889                     9.8k  
890                      38k  

[891 rows x 7 columns]

In [51]:
df.iloc[0]

Unnamed: 0                                                                134
course_title                (ISC)² Systems Security Certified Practitioner...
course_organization                                                    (ISC)²
course_Certificate_type                                        SPECIALIZATION
course_rating                                                             4.7
course_difficulty                                                    Beginner
course_students_enrolled                                                 5.3k
Name: 0, dtype: object

In [62]:
df.iloc[-1]

Unnamed: 0                                                                163
course_title                    Финансовые инструменты для частного инвестора
course_organization         National Research University Higher School of ...
course_Certificate_type                                        SPECIALIZATION
course_rating                                                             4.7
course_difficulty                                                    Beginner
course_students_enrolled                                                  38k
Name: 890, dtype: object

In [65]:
df[['course_title','course_difficulty']]

course_title course_difficulty
0    (ISC)² Systems Security Certified Practitioner...          Beginner
1    A Crash Course in Causality:  Inferring Causal...      Intermediate
2                       A Crash Course in Data Science             Mixed
3                              A Law Student's Toolkit             Mixed
4                  A Life of Happiness and Fulfillment             Mixed
..                                                 ...               ...
886                         Программирование на Python      Intermediate
887               Психолингвистика (Psycholinguistics)             Mixed
888       Разработка интерфейсов: вёрстка и JavaScript      Intermediate
889                            Русский как иностранный      Intermediate
890      Финансовые инструменты для частного инвестора          Beginner

[891 rows x 2 columns]